SceneTrip/urls.py
from django.contrib import admin
from django.urls import path, include
from locations import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('api/accounts/', include("accounts.urls")),
    path('api/journals/', include("journals.urls")),
    path('api/communities/', include("communities.urls")),
    path('api/locations/', include("locations.urls")),
    path('api/questions/', include("questions.urls")),
    path('api/chats/', include('chats.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from .views import (
    SignupAPIView, SocialLoginView, VerifyEmailAPIView, LogoutAPIView, SubscribeView,  
    PasswordResetRequestView, PasswordResetConfirmView, EmailResetRequestView, EamilResetConfirmView, 
    MyJournalsListAPIView, SavedLocationsListAPIView, LikeJournalsListAPIView, SubscribingsListAPIView, 
    SubsribingsjournalAPI, MyCommunityListAPIView, DeleteAPIView, VerifyjJournalEmailAPIView, 
    SocialCallbackView, LoginView, UserInfoView, SetNicknameView, mypage, EditProfileView
)

app_name = 'accounts'

urlpatterns = [
    path("signup/", SignupAPIView.as_view(), name="signup"), # 회원가입
    path("login-page/", LoginView.as_view(), name="login_page"),  # 로그인 페이지를 위한 경로
    path("login/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("<str:nickname>/subscribes/", SubscribeView.as_view(), name="subscribes"), # 구독
    path('verify/<str:token>/', VerifyEmailAPIView.as_view(), name='verify_email'), # 회원가입 이메일 인증, 이 path 없으면 이메일 인증시 Not Found 에러 발생
    path('journalists/verify/<str:token>', VerifyjJournalEmailAPIView.as_view(), name='verify_journalemail'), # 회원가입 grade가 저널일 경우
    path('passwordreset/', PasswordResetRequestView.as_view(), name='password_reset'), # 비밀번호 초기화
    path('passwordchange/verify/<str:token>/', PasswordResetConfirmView.as_view(), name='passwordverifyemail'), # 비밀번호 변경 이메일 인증
    path('emailreset/', EmailResetRequestView.as_view(), name='email_reset'), # 이메일 초기화
    path('emailchange/verify/<str:token>/', EamilResetConfirmView.as_view(), name='emailverifyemail'), # 이메일변경 이메일 인증


    ######## 마이페이지 관련된 url
    path("token/refresh/", TokenRefreshView.as_view(), name="token_refresh"), # 리프레시 토큰
    path("logout/", LogoutAPIView.as_view(), name="logout"), # 로그아웃


    path('<str:nickname>/mypage/journallike/', LikeJournalsListAPIView.as_view(), name='journal_like'), # 내가 좋아요한 저널 글 목록
    path('<str:nickname>/mypage/myjournals/', MyJournalsListAPIView.as_view(), name='my_journals'), # 내가 쓴 글 전체보기
    path('<str:nickname>/mypage/savedlocations/', SavedLocationsListAPIView.as_view(), name='saved_locations'), # 저장한 촬영지 전체보기
    path('<str:nickname>/mypage/subscribings/', SubscribingsListAPIView.as_view(), name='subscribings'), # 내가 구독한 사람 전체보기
    path('<str:nickname>/mypage/communitiesauthor/', MyCommunityListAPIView.as_view(), name='my_communities'), # 내가 쓴 커뮤니티 글 전체보기
    path('<str:nickname>/mypage/<str:sub_nickname>/', SubsribingsjournalAPI.as_view(), name='subscribings_journal'), # 내가 구독한 인원 글 보기

    # 회원탈퇴
    path('<str:nickname>/delete/', DeleteAPIView.as_view(), name='accounts_delete'), # 회원탈퇴
    path('user-info/', UserInfoView.as_view(), name='user_info'),  # 사용자 정보 API
    
    path("<str:nickname>/mypage/", mypage, name='my_page'),


    # 소셜 로그인
    path('kakaologinpage/', views.kakaologinpage, name='kakaologinpage'),
    path('social/login/<str:provider>/', SocialLoginView.as_view() ,name='kakao-login'),  # 카카오 로그인 URL
    path('social/callback/<str:provider>/', SocialCallbackView.as_view(), name='kakao-callback'),  # 카카오 콜백 URL
    path('set_nickname/', SetNicknameView.as_view(), name='set-nickname'),
    path('<str:nickname>/edit/', EditProfileView.as_view(), name='edit_profile'), #회원정보 수정
]

chats/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='chat_index'),
    path('<str:room_name>/', views.room, name='room'),
]

locations/urls.py
from django.urls import path
from .views import LocationListAPIView, LocationSearchAPIView, LocationRegionAPIView, LocationDetailAPIView, LocationSaveView, LocationListView, location_detail, AiPlanningAPIView

app_name = "locations"

urlpatterns = [
    path("lists/", LocationListAPIView.as_view(), name="location-list"), # 촬영지 목록 조회
    path("search/", LocationSearchAPIView.as_view(), name="location-search"), # 촬영지 검색
    path("lists/<str:region>/", LocationRegionAPIView.as_view(), name="location-region-list"), # 촬영지 지역별 조회
    path("lists/detail/<int:pk>/", LocationDetailAPIView.as_view(), name="location-detail"), # 촬영지 상세조회
    path("<int:id>/saves/", LocationSaveView.as_view(), name="location-save"), # 촬영지 저장
    # path("lists/plans/"),
    path('list/', LocationListView.as_view(), name='location_list'),
    path('<int:pk>/', location_detail, name='location_detail'),
    path("plans/", AiPlanningAPIView.as_view(), name="trip-planning"), # AI 여행 플래닝 서비스
]

locations/models.py
from django.db import models
from django.contrib.auth import get_user_model


class Location(models.Model):
    id = models.IntegerField(primary_key=True)
    media_type = models.CharField(max_length=20)
    title = models.CharField(max_length=300)
    place_name = models.CharField(max_length=300)
    place_type = models.CharField(max_length=100)
    place_description = models.TextField(max_length=300)
    opening_hours = models.TextField(max_length=300)
    break_time = models.CharField(max_length=100)
    closed_day = models.CharField(max_length=100)
    address = models.CharField(max_length=300)
    latitude = models.FloatField(max_length=8)
    longitude = models.FloatField(max_length=10)
    tel = models.CharField(max_length=20)
    created_at = models.CharField(max_length=10)
    save_count = models.IntegerField(default=0)


class LocationSave(models.Model):
    User = get_user_model()

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="location_save")
    location = models.ForeignKey(Location, on_delete=models.CASCADE, default=1)
    saved_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        unique_together = ('user', 'location')

locations/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView
from django.urls import reverse
from django.db.models import Q, Count, Value
from django.conf import settings
from django.db.models.functions import Replace, Lower
from rest_framework import status
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from langchain_openai import ChatOpenAI
from langchain.prompts import PromptTemplate
from langchain.chains import LLMChain
from journals.models import Journal
from communities.models import Community
from .models import Location, LocationSave
from .serializers import LocationSerializer
import re
import urllib
import json


def custom_sort_key(value):
    # 한글, 알파벳, 숫자, 특수기호 순으로 정렬
    if re.match(r"^[가-힣]", value):
        return (0, value)
    elif re.match(r"^[a-zA-Z]", value):
        return (1, value)
    elif re.match(r"^[0-9]", value):
        return (2, value)
    else:
        return (3, value)


class LocationListAPIView(APIView):
    # 촬영지 목록 조회
    def get(self, request):
        sort_by = request.query_params.get('sort_by', 'title') # parameter로 sort_by를 따로 지정해주지 않으면 title이 default.
        location_data = Location.objects.values('id', 'title', 'place_name', 'save_count')
        
        if sort_by == 'title':
            # 제목으로 정렬. 위의 custom_sort_key에 따라 정렬.
            sorted_location_data = sorted(location_data, key=lambda x: custom_sort_key(x['title']))
        elif sort_by == 'popularity':
            # 저장수에 따라 정렬. 많이 저장된 촬영지 == 인기 촬영지.
            sorted_location_data = sorted(location_data, key=lambda x: x['save_count'], reverse=True)
        else:
            return Response({"error": "Invalid sort_by parameter"}, status=status.HTTP_400_BAD_REQUEST)

        return Response(sorted_location_data)
    
    
class LocationListView(ListView):
    model = Location
    template_name = 'locations/location_list.html'
    context_object_name = 'locations'
    paginate_by = 12  # 한 페이지에 표시할 촬영지 수
    
    def get_queryset(self):
        queryset = super().get_queryset()
        keyword = self.request.GET.get('keyword', None)
        filter_by = self.request.GET.get('filter', 'title')  # 기본값: 제목 검색
        sort_by = self.request.GET.get('sort', 'title')  # 기본 정렬: 제목순

        # 검색어가 있을 경우 분류에 따라 필터링
        if keyword:
            filters = Q()

            if filter_by == 'all':  # 'all'은 모든 필드에서 검색할 때 사용
                filter_fields = ["media_type", "title", "place_name", "place_type", "place_description", "address"]
                for field in filter_fields:
                    filters |= Q(**{f"{field}__icontains": keyword})
            else:
                # 특정 필드에 대해서만 검색 (예: title, address 등)
                filters |= Q(**{f"{filter_by}__icontains": keyword})

            queryset = queryset.filter(filters)
            
        # 정렬 방식 적용
        if sort_by == 'popularity':
            queryset = queryset.order_by('-save_count')  # 저장 수를 기준으로 내림차순 정렬
        elif sort_by == 'title':
            # 커스텀 정렬을 사용하기 위해 Python의 sorted() 사용
            queryset = sorted(queryset, key=lambda location: custom_sort_key(location.title))

        return queryset
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        page_obj = context['page_obj']

        # 현재 페이지와 페이지 그룹을 계산
        current_page = page_obj.number
        current_group = (current_page - 1) // 5 + 1
        start_page = (current_group - 1) * 5 + 1
        end_page = start_page + 4

        # 총 페이지 수를 넘지 않도록 조정
        if end_page > page_obj.paginator.num_pages:
            end_page = page_obj.paginator.num_pages

        # 템플릿으로 start_page와 end_page 전달
        context['page_range'] = range(start_page, end_page + 1)
        context['current_sort'] = self.request.GET.get('sort', 'title')  # 현재 정렬 방식도 전달
        return context
    

class LocationRegionAPIView(APIView):
    # 촬영지 지역별 조회
    def get(self, request, region, *args, **kwargs):
        regions = [
            '경기도', '서울특별시', '인천광역시', '강원도', '경상남도', '경상북도', 
            '광주광역시', '대구광역시', '대전광역시', '울산광역시', '부산', # 부산광역시의 경우 '부산'으로만 기록되어 있는 데이터도 있어서.
            '전라남도', '전라북도', '제주특별자치도', '충청남도', '충청북도', '세종특별자치시'
        ]

        if region not in regions:
            return Response({"error": "Invalid region"}, status=400)
        
        region_data = {}
        location_data = Location.objects.filter(address__contains=region).values('id', 'title', 'place_name', 'save_count')

        sort_by = request.query_params.get('sort_by', 'title') # parameter로 sort_by를 따로 지정해주지 않으면 title이 default.
        
        if sort_by == 'title':
            # 제목으로 정렬. 위의 custom_sort_key에 따라 정렬.
            sorted_data = sorted(location_data, key=lambda x: custom_sort_key(x['title']))
        elif sort_by == 'popularity':
            # 저장수에 따라 정렬. 많이 저장된 촬영지 == 인기 촬영지.
            sorted_data = sorted(location_data, key=lambda x: x['save_count'], reverse=True)
        else:
            return Response({"error": "Invalid sort_by parameter"}, status=status.HTTP_400_BAD_REQUEST)
        
        region_data[region] = sorted_data

        return Response(region_data)


class LocationDetailAPIView(APIView):
    # 촬영지 상세조회
    def get(self, request, pk):
        location = get_object_or_404(Location, pk=pk)
        serializer = LocationSerializer(location)
        return Response(serializer.data)


class LocationSearchAPIView(APIView):
    # 촬영지 검색
    def get(self, request, *args, **kwargs):
        query_params = request.query_params
        search_value = query_params.get("keyword", None) # 검색 keyword
        filter_fields = ["media_type", "title", "place_name", "place_type", "place_description", "address"]

        filters = Q()
        if search_value:
            for field in filter_fields:
                filters |= Q(**{f"{field}__icontains": search_value})

        location_data = Location.objects.filter(filters).values('id', 'title', 'place_name', 'save_count')
        sorted_location_data = sorted(location_data, key=lambda x: custom_sort_key(x['title']))
        
        # 키워드에 해당하는 검색결과가 없을 때.
        if not location_data or search_value.strip() == "":
            return Response({"message": "검색 결과가 없습니다"}, status=status.HTTP_200_OK)

        return Response(sorted_location_data, status=status.HTTP_200_OK)


class LocationSaveView(APIView):
    permission_classes = [IsAuthenticated]
    

    def post(self, request, id):
        user = request.user
        location = get_object_or_404(Location, id=id)
        location_save, created = LocationSave.objects.get_or_create(user=user, location=location)

        if created:
            location.save_count += 1
            location.save()
            location_save.save()
            return Response({"message": "촬영지 정보가 저장되었습니다."}, status=status.HTTP_201_CREATED)
        else:
            location.save_count -= 1
            location.save()
            location_save.delete()
            return Response({"message": "촬영지 정보가 삭제되었습니다."}, status=status.HTTP_204_NO_CONTENT)


def get_nearby_place(place_name):
        client_id = settings.NAVER_CLIENT_ID
        client_secret = settings.NAVER_SECRET_KEY
        
        if not place_name:
            return Response({"error": "place_name is required"}, status=status.HTTP_400_BAD_REQUEST)
        
        place_name_for_search = ''.join(place_name.strip().split())
        
        try:
            location = Location.objects.annotate(place_name_no_spaces=Replace('place_name', Value(' '), Value(''))).filter(place_name_no_spaces__icontains=place_name_for_search).first()
            if not location:
                return Response({"error": f"No location found for place_name '{place_name}'"}, status=status.HTTP_404_NOT_FOUND)
            address = location.address
            print(address)
            short_address = " ".join(address.split()[:2])
        except Exception as e:
            return Response({"error": f"Error retrieving address: {str(e)}"}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)
        
        nearby_places = []
        categories = ["식당", "관광지", "숙소"]
    
        for category in categories:
            query = f"{short_address} 근처 {category}"
            encText = urllib.parse.quote(query)
            url = f"https://openapi.naver.com/v1/search/local.json?query={encText}&display=5&start=1&sort=comment"
            
            try:
                req = urllib.request.Request(url)
                req.add_header("X-Naver-Client-Id", client_id)
                req.add_header("X-Naver-Client-Secret", client_secret)
                response = urllib.request.urlopen(req)
                rescode = response.getcode()
                
                if rescode == 200:
                    response_body = response.read()
                    result = json.loads(response_body)
                    if 'items' in result and result['items']:
                        for item in result['items']:
                            nearby_places.append({
                                "title": item['title'], # 업체명, 기관명
                                "link": item.get('link'), # 업체, 기관의 상세정보(URL)
                                "category": item.get('category'), # 업체, 기관의 분류 정보
                                "roadaddress": item.get('roadAddress'), # 도로명 주소
                                "address": item.get('address') # 지번 주소
                            })
                else:
                    return {"error": f"Error Code: {rescode}"}
                    
            except urllib.error.URLError as e:
                return {"error": f"Error occurred: {str(e)}"}
    
        return nearby_places


class AiPlanningAPIView(APIView):
        def get(self, request):
            return render(request, 'locations/plan.html')
        
        def post(self, request):

locations/templates/locations/location_detail.html
{% extends 'base.html' %}

{% block title %}
{{ location.title }} - 촬영지 정보
{% endblock %}

{% block content %}
<div class="container mt-5">
  <h1>{{ location.title }}</h1>
  <p><strong>장소 이름:</strong> {{ location.place_name }}</p>
  <p><strong>설명:</strong> {{ location.place_description }}</p>
  <p><strong>영업 시간:</strong> {{ location.opening_hours }}</p>
  <p><strong>휴식 시간:</strong> {{ location.break_time }}</p>
  <p><strong>휴무일:</strong> {{ location.closed_day }}</p>
  <p><strong>주소:</strong> {{ location.address }}</p>
  <p><strong>전화번호:</strong> {{ location.tel }}</p>
  <p><strong>저장 수:</strong> {{ location.save_count }}</p>
  <p><strong>미디어 타입:</strong> {{ location.media_type }}</p>
  <p><strong>장소 타입:</strong> {{ location.place_type }}</p>

  <!-- 촬영지 저장 버튼 -->
  <div class="mt-4">
    <button id="save-location-btn" class="btn btn-success" style="color:#5D4037; background-color:#FFFDE7; border:none;">촬영지 저장</button> &nbsp
    <a href="{% url 'locations:location_list' %}" class="btn btn-secondary" style="color:#5D4037; background-color:#E0E0E0; border:none;">목록으로 돌아가기</a>
  </div>
</div>

<script>
  document.getElementById('save-location-btn').addEventListener('click', function() {
    const accessToken = localStorage.getItem('access_token');
    
    if (!accessToken) {
      alert('로그인 후 이용해주세요.');
      window.location.href = "{% url 'accounts:login_page' %}";
      return;
    }

    // location.id 값을 JavaScript로 넘겨줌
    fetch(`/api/locations/{{ location.id }}/saves/`, {  // 중괄호 안에 location.id 적용
      method: "POST",
      headers: {
        'Authorization': `Bearer ${accessToken}`,
      }
    })
    .then(response => {
      if (!response.ok) {
        throw new Error('촬영지 저장 실패');
      }
      return response.json();
    })
    .then(data => {
      alert(data.message);
    })
    .catch(error => {
      console.error('에러 발생:', error);
      alert('촬영지 저장 중 문제가 발생했습니다.');
    });
  });
</script>
{% endblock %}

locations/templates/locations/location_list.html
{% extends 'base.html' %}

{% block title %}
촬영지 목록
{% endblock %}

{% block content %}
<style>
  .filter-select {
    max-width: 110px; /* 드롭다운 크기 조정 */
  }
  
  .search-input {
    margin-right: 10px; /* 검색창과 버튼 사이 여백 추가 */
    flex-grow: 1; /* 검색창이 더 넓어지도록 설정 */
  }
  
  .search-btn {
    padding-left: 20px;
    padding-right: 20px;
  }
</style>

<head>
  <title>Button Placement</title>
    <style>
      #container a {
        position: absolute;
        top: 120px; 
        right: 30px; 
        display: flex;
        gap: 10px; 
        color: black;
        background-color: #F2F0EB;
        padding: 10px 20px;
        border-radius: 5px;
        text-decoration: none;
      }

      #container a:hover {
        background-color: #AAFA82;
        cursor: pointer;
      }
      /* 드롭다운 크기 조정 */
      .sort-select {
        width: auto !important; /* 텍스트 길이에 맞게 자동 조정, 중요도 높이기 */
        display: inline-block !important; /* 드롭다운의 폭을 최소로 설정 */
        max-width: 150px; /* 최대 너비를 제한하여 너무 넓어지지 않도록 */
      }
    </style>
</head>

<div id="container">
  <a href="{% url 'locations:trip-planning' %}"><strong>🤖 AI 여행 플래닝</strong></a>
</div>
<div class="container mt-5">
  <h1>촬영지 목록</h1>

  <br>
  
  <form method="GET" action="{% url 'locations:location_list' %}" class="mb-4">
    <div class="input-group mb-3">
      <select name="filter" class="form-select form-select-sm filter-select">
        <option value="all" {% if request.GET.filter == 'all' %}selected{% endif %}>통합 검색</option>
        <option value="title" {% if request.GET.filter == 'title' %}selected{% endif %}>작품</option>
        <option value="address" {% if request.GET.filter == 'address' %}selected{% endif %}>주소</option>
      </select>
      <input type="text" name="keyword" class="form-control search-input mx-2" placeholder="검색어 입력" value="{{ request.GET.keyword }}">
      <div class="input-group-append">
        <button type="submit" class="btn btn-primary search-btn" style="background-color:#546E7A; border: none;">검색</button>
      </div>
    </div>
  </form>

  <br>

  <form method="GET" action="{% url 'locations:location_list' %}" class="d-flex justify-content-start mb-3">
    <div class="input-group">
      <select class="form-select form-select-sm sort-select" onchange="location = this.value;">
        <option value="?filter={{ request.GET.filter }}&keyword={{ request.GET.keyword }}&sort=title" {% if request.GET.sort == 'title' %}selected{% endif %}>제목순 정렬</option>
        <option value="?filter={{ request.GET.filter }}&keyword={{ request.GET.keyword }}&sort=popularity" {% if request.GET.sort == 'popularity' %}selected{% endif %}>인기순 정렬</option>
      </select>
    </div>
  </form>

  <br>

  <div class="row">
    {% for location in page_obj %}
    <div class="col-md-4 mb-4">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">{{ location.title }}</h5>
          <p class="card-text"><strong>장소 이름:</strong> {{ location.place_name }}</p>
          <p class="card-text"><small>저장 수: {{ location.save_count }}</small></p>
          <a href="{% url 'locations:location_detail' location.id %}" class="btn btn-primary" style="background-color:#546E7A; border: none;">자세히 보기</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>


  <br>

  <!-- 페이지네이션 -->
  <nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?filter={{ request.GET.filter }}&keyword={{ request.GET.keyword }}&page=1" aria-label="처음">
          <span aria-hidden="true">&laquo;&laquo;</span>
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?filter={{ request.GET.filter }}&keyword={{ request.GET.keyword }}&page={{ page_obj.previous_page_number }}" aria-label="이전">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      {% endif %}

      {% for num in page_range %}
        {% if page_obj.number == num %}
        <li class="page-item active">
          <a class="page-link" href="?filter={{ request.GET.filter }}&keyword={{ request.GET.keyword }}&page={{ num }}" style="background-color:#546E7A; border: none;">{{ num }}</a>
        </li>
        {% else %}
        <li class="page-item">
          <a class="page-link" href="?filter={{ request.GET.filter }}&keyword={{ request.GET.keyword }}&page={{ num }}" style="background-color:#546E7A; border: none;">{{ num }}</a>
        </li>
        {% endif %}
      {% endfor %}
      
      {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?filter={{ request.GET.filter }}&keyword={{ request.GET.keyword }}&page={{ page_obj.next_page_number }}" aria-label="다음" style="background-color:#546E7A; border: none;">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?filter={{ request.GET.filter }}&keyword={{ request.GET.keyword }}&page={{ page_obj.paginator.num_pages }}" aria-label="마지막" style="background-color:#546E7A; border: none;">
          <span aria-hidden="true">&raquo;&raquo;</span>
        </a>
      </li>
      {% endif %}
    </ul></nav>
    {% endblock %}

locations/templates/locations/plan_result.html
{% extends 'base.html' %}  
{% block title %} 여행 플래닝 서비스 {% endblock %}  

{% block content %}  
<head>     
    <title>여행 계획 결과</title>     
    <style>         
        body {             
            font-family: Arial, sans-serif;             
            margin: 20px;             
            padding: 0;             
            position: relative; /* Ensure that the body is positioned for absolute elements */         
            padding-top: 60px;
        }         
        h1 {             
            color: #333;         
        }         
        .travel-plan {             
            border: 1px solid #ccc;             
            padding: 45px;       
            border-radius: 25px;      
            background-color: #FAFAFA;             
            margin-top: 20px;         
        }         
        .error {             
            color: red;         
        }         
        .recreate-button {             
            display: block;             
            width: 200px; /* Width of the button */             
            margin: 20px auto; /* Center horizontally with margin auto */             
            padding: 10px; /* Padding for button look */             
            text-align: center; /* Center text inside the button */             
            background-color: #0B3B24; /* Button background color */             
            color: white; /* Button text color */             
            text-decoration: none; /* Remove underline from link */             
            border-radius: 5px; /* Rounded corners */             
            font-weight: bold; /* Bold text */             
        }         
        .recreate-button:hover {             
            background-color: #0B3B0B; /* Darker shade on hover */         
        }     
    </style> 
</head>

<body>      
    <h1>여행 계획 결과</h1>      
    <h5>여행계획 생성에 시간이 소요됩니다. 적절한 결과가 나오지 않았다면 잠시 후 새로고침을 눌러주세요.</h5>      

    {% if travel_plan %}         
        <div class="travel-plan">             
            <h2>여행 계획</h2>             
            <p>{{ travel_plan|safe|linebreaks }}</p>         
        </div>     
    {% else %}         
        <div class="error">             
            <p> </p>         
        </div>     
    {% endif %}      

    <a class="recreate-button" href="{% url 'locations:trip-planning' %}">여행 계획 다시 생성하기</a>  
    <br><br>
</body>  
{% endblock %}